databases:

- id: local_address
  type: sentinel.db.address.local.AddressDB
  description: >
    Monitored Addresses
  parameters:
    path: ./examples/balance_monitor/data/address.list 

- id: local_address_0x00
  type: sentinel.db.address.local.AddressDB
  description: >
    Monitored Addresses
  parameters:
    path: ./examples/balance_monitor/data/address-0x00.list 

- id: local_address_anvil
  type: sentinel.db.address.local.AddressDB
  description: >
    Monitored Addresses
  parameters:
    path: ./examples/balance_monitor/data/address-anvil.list 

- id: local_bridge_address_hai_eth
  type: sentinel.db.address.local.AddressDB
  description: >
    Monitored Addresses
  parameters:
    path: ./examples/balance_monitor/data/address-bridge-HAI-eth.list 

- id: local_bridge_address_hai_bsc
  type: sentinel.db.address.local.AddressDB
  description: >
    Monitored Addresses
  parameters:
    path: ./examples/balance_monitor/data/address-bridge-HAI-bsc.list 

- id: address_weth
  type: sentinel.db.address.local.AddressDB
  description: >
    Monitored Addresses
  parameters:
    path: ./examples/balance_monitor/data/address-weth.list 
