inputs:

# Kafka Transactions

- id: kafka_eth_transactions
  type: sentinel.channels.kafka.transactions.InboundTransactionsChannel
  parameters:
    bootstrap_servers: {{ env['KAFKA_BOOTSTRAP_SERVERS'] }}
    group_id: sentinel.balance-monitor.tx
    # group_id: sentinel-public.transactions
    auto_offset_reset: latest
    topics: 
    - {{ env['KAFKA_INBOUND_ETH_TX_TOPIC'] }}

- id: kafka_bsc_transactions
  type: sentinel.channels.kafka.transactions.InboundTransactionsChannel
  parameters:
    bootstrap_servers: {{ env['KAFKA_BOOTSTRAP_SERVERS'] }}
    group_id: sentinel.balance-monitor.tx
    # group_id: sentinel-public.transactions
    auto_offset_reset: latest
    topics: 
    - {{ env['KAFKA_INBOUND_BSC_TX_TOPIC'] }}

# Websocket Transactions

- id: ws_eth_transactions
  type: sentinel.channels.ws.transactions.InboundTransactionChannel
  parameters:
    server_uri: {{ env['ETH_WS_URL'] }}

- id: ws_transactions_localhost
  type: sentinel.channels.ws.transactions.InboundTransactionChannel
  parameters:
    server_uri: ws://localhost:9300

# Local filesystem transactions

- id: fs_transactions
  type: sentinel.channels.fs.transactions.InboundTransactionsChannel
  parameters:
    path: ./data/transactions.json
