outputs:

- id: kafka_events
  type: sentinel.channels.kafka.events.OutboundEventsChannel
  parameters:
    bootstrap_servers: {{ env['KAFKA_BOOTSTRAP_SERVERS'] }}
    topics: 
    - {{ env['KAFKA_OUTBOUND_EVENT_TOPIC']}}

- id: fs_events
  type: sentinel.channels.fs.common.OutboundFileChannel
  parameters:
    record_type: sentinel.models.event.Event
    path: ./events/EVENTS.json
    mode: overwrite

- id: http_events
  type: sentinel.channels.http.outbound.OutboundEventsChannel
  parameters:
    endpoint: {{ env["EXT_HTTP_URL"] }} 
    token: {{ env['EXT_API_TOKEN'] }}
    chain_id: 1
    network: ethereum
    metadata:
      origin: simulation
