#!/bin/bash -e

source scripts/common

./scripts/cleanup

SENTINEL_VERSION=$(${PREFIX}setuptools-git-versioning)
echo ${SENTINEL_VERSION} > src/sentinel/VERSION

echo "[INFO] Building Sentinel SDK" \
    && ${PREFIX}python3 -m build \
&& echo "[INFO] Distribution files check" \
    && ${PREFIX}twine check dist/*

echo "[INFO] Build Sentinel SDK Documentation [NOT IMPLEMENTED]"
# ${PREFIX}mkdocs build
