#!/bin/bash -e

source scripts/common

./scripts/cleanup

echo "[INFO] Building Sentinel SDK" \
    && ${PREFIX}hatch -v build --clean \
&& echo "[INFO] Distribution files check" \
    && ${PREFIX}twine check dist/*

echo "[INFO] Build Sentinel SDK Documentation [NOT IMPLEMENTED]"
# ${PREFIX}mkdocs build
