#!/bin/bash -e

source scripts/common

export SOURCE_FILES="src tests"

# ./scripts/sync-version
${PREFIX}ruff format --check --diff $SOURCE_FILES

# ${PREFIX}mypy $SOURCE_FILES

${PREFIX}ruff check $SOURCE_FILES