#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

export SOURCE_FILES="src tests"

# ./scripts/sync-version
${PREFIX}ruff format --check --diff $SOURCE_FILES

# ${PREFIX}mypy $SOURCE_FILES

${PREFIX}ruff check $SOURCE_FILES