#!/bin/bash -e

source scripts/common

if [ -d 'dist' ] ; then
    echo "[INFO] Removing dist/ directory"
    rm -r dist
fi

if [ -d 'site' ] ; then
    echo "[INFO] Removing site/ directory"
    rm -r site
fi

if [ -d 'htmlcov' ] ; then
    echo "[INFO] Removing htmlcov/ directory"
    rm -r htmlcov
fi

if [ -d 'junit' ] ; then
    echo "[INFO] Removing junit/ directory"
    rm -r junit
fi

# if [ -d "src/${PACKAGE}.egg-info" ] ; then
#     echo "[INFO] Removing src/${PACKAGE}.egg-info directory"
#     rm -r "src/${PACKAGE}.egg-info"
# fi

rm -rf src/*.egg-info

find examples/ -type f -name "*.py[co]" -delete
find examples/ -type d -name __pycache__ -delete

find src/${PACKAGE} -type f -name "*.py[co]" -delete
find src/${PACKAGE} -type d -name __pycache__ -delete
