#!/bin/sh -e

source scripts/common

if [ -d 'dist' ] ; then
    rm -r dist
fi

if [ -d 'site' ] ; then
    rm -r site
fi

if [ -d 'htmlcov' ] ; then
    rm -r htmlcov
fi

if [ -d 'junit' ] ; then
    rm -r junit
fi

if [ -d "${PACKAGE}.egg-info" ] ; then
    rm -r "${PACKAGE}.egg-info"
fi

find src/${PACKAGE} -type f -name "*.py[co]" -delete
find src/${PACKAGE} -type d -name __pycache__ -delete
