#!/bin/bash -e

source scripts/common

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

VENV=".venv"

if [ -z "$GITHUB_ACTIONS" ]; then
    source scripts/venv
    PIP="$VENV/bin/pip"
else
    PIP="pip"
fi

function deployment-tools() {

    echo "[INFO] Install/Upgrade pip" \
        && ${PREFIX}python -m pip install --upgrade pip

    echo "[INFO] Install development tools and libs" \
        && ${PREFIX}pip install \
            build \
            twine \
            hatch
            # setuptools
            # setuptools-git-versioning \

}

function dev-tools() {

    echo "[INFO] Install development tools and libs" \
        && ${PREFIX}pip install \
            ruff \
            pytest \
            pytest-asyncio \
            pytest-cov
}

function sentinel() {

    echo "[INFO] Install ext-sentinel-py-sdk package" && \
        ${PREFIX}pip install -e .
}

function all() {

    deployment-tools \
    && dev-tools \
    && sentinel
}

$@
