#!/bin/bash -e

source scripts/common

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

if [ -z "$GITHUB_ACTIONS" ]; then
    PIP=".venv/bin/pip"
else
    PIP="pip"
fi

function help() {

    echo "Usage: ./scripts/install <option>"
    echo
    echo "Options:"
    echo "  help                - show this help"
    echo "  deployment-tools    - install deloyment tools: build, twine, hatch"
    echo "  dev-tools           - install dev tools: ruff, pytest, ..."
    echo "  sentinel            - install Sentinel SDK in editable mode"
    echo "  all                 - install deployment and dev tools, Sentinel SDK"
    echo
}


function deployment-tools() {

    echo "[INFO] Install/Upgrade pip" \
        && ${PREFIX}python -m pip install --upgrade pip

    echo "[INFO] Install development tools and libs" \
        && ${PREFIX}pip install \
            build==1.2.1 \
            twine==5.1.1 \
            hatch==1.12.0 \
            hatchling==1.25.0

}

function dev-tools() {

    echo "[INFO] Install development tools and libs" \
        && ${PREFIX}pip install \
            ruff==0.4.10 \
            pytest==8.2.2 \
            pytest-asyncio==0.23.7 \
            pytest-aiohttp==1.0.5 \
            pytest-benchmark==4.0.0 \
            pytest-cov==5.0.0
}

function sentinel() {

    echo "[INFO] Install ext-sentinel-py-sdk package" && \
        ${PREFIX}pip install -e .
}

function all() {

    deployment-tools \
    && dev-tools \
    && sentinel
}

$@
