#!/usr/bin/env bash

# to terminate as soon as any command it executes fails, 
# i.e., returns a non-zero exit status. 
set -e

VERSION_FILE="src/sentinel/version.py"

help() {

    echo "./scripts/release <command>"
    echo
    echo "  current-version:        show current version"
    echo "  bump-release-version:   bump release version"
    echo "  bump-next-version:      bump next version"
    echo
}

set-bot-name() {

    git config --local user.name "github-actions[bot]"
    git config --local user.email "github-actions[bot]@users.noreply.github.com"
}

commit-version() {

    CURRENT_VERSION=${1:-}
    NEXT_VERSION=${2:-}

    git add ${VERSION_FILE}
    git commit -m "Bump version: ${CURRENT_VERSION} → ${NEXT_VERSION}"
}

current-version() {

    CURRENT_VERSION=`hatchling version`
    echo "[INFO] Current version: ${CURRENT_VERSION}"
}

bump-release-version() {

    CURRENT_VERSION=`hatchling version`
    hatchling version release
    NEXT_VERSION=`hatchling version`
    commit-version ${CURRENT_VERSION} ${NEXT_VERSION}
}

bump-next-version() {

    CURRENT_VERSION=`hatchling version`
    hatchling version fix,dev
    NEXT_VERSION=`hatchling version`
    commit-version ${CURRENT_VERSION} ${NEXT_VERSION}
}

# git push
# git push --tags


$@