#!/bin/sh -e

SEMVER_REGEX="([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?"
CHANGELOG_VERSION=$(grep -o -E $SEMVER_REGEX docs/Release-Notes.md | head -1)
VERSION=$(grep -o -E $SEMVER_REGEX src/sentinel/version.py | head -1)
if [ "$CHANGELOG_VERSION" != "$VERSION" ]; then
    echo "Version in changelog does not match version in src/sentinel/version.py!"
    exit 1
fi