#!/bin/bash -e

source scripts/common


# if [ -z $GITHUB_ACTIONS ]; then
#     scripts/check
# fi

# ${PREFIX}coverage run -m pytest $@

# if [ -z $GITHUB_ACTIONS ]; then
#     scripts/coverage
# fi

# ruff --output-format=github .

# hatch fmt --check
# hatch run types:check

pytest --junitxml=junit/test-results-${PYTHON_VERSION}.xml

# hatch run full
