#!/usr/bin/env python3

import json
import asyncio
import logging
import argparse
import websockets

from rich.logging import RichHandler


logger = logging.getLogger(__name__)


async def run(uri: str) -> None:

    try:
        async with websockets.connect(uri) as ws_server:
            async for msg in ws_server:
                record = json.loads(msg)                
                logger.info(record)
    finally:
        logger.info("Closing connection to websocket channel")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--log-level", default="INFO", help="Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL")
    parser.add_argument("--uri", type=str, required=True, help="Websocket URI")
    args = parser.parse_args()

    logging.basicConfig(
        level=args.log_level,
        format="%(asctime)s.%(msecs)03d (%(processName)s::%(name)s:%(lineno)d) %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%S",
        handlers=[RichHandler(rich_tracebacks=True)],
    )
    try:
        asyncio.run(run(uri=args.uri))
    except KeyboardInterrupt:
        logger.info("Interrupted by user")
