FROM ext/sentinel/base:0.3.0


RUN echo "[INFO] Creating sentinel user" \
        && adduser -D -u 1000 -s /usr/local/bin/fish sentinel \
        && echo 'sentinel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Add repository code
WORKDIR /opt/sentinel/

USER sentinel

# Copy Balance Monitor code
COPY *.py /opt/sentinel/
COPY data /opt/sentinel/data
#COPY . /opt/sentinel/

COPY profile-ws-events-bridge-HAI-eth.yaml /opt/sentinel/profile.yaml
COPY env-dev.yaml /opt/sentinel/env.yaml

CMD ["launch","--profile","/opt/sentinel/profile.yaml","--env-vars","/opt/sentinel/env.yaml"]
ENTRYPOINT [ "sentinel" ]
