name: dev-merge

on:
  push:
    branches: [ "main" ]

env:
  PYTHON_VERSION: "3.11"

jobs:

  dev-merge:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Install deployment/dev tools & sentinel sdk
      run: |
        ./scripts/install all

    - name: Run tests
      run: |
        ./scripts/test ${{ matrix.python-version }}

    - name: Bumping dev version
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        CURRENT_VERSION=`hatch version`
        hatch version dev
        NEXT_VERSION=`hatch version`
        # git add src/sentinel/version.py
        # git commit -m "Bump dev version: $CURRENT_VERSION → $NEXT_VERSION"
        # git push
