name: merge-to-main

on:
  push:
    branches: [ "main" ]

jobs:

  merge-to-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade hatch
        pip install --upgrade pytest pytest-asyncio pytest-cov

    - name: Install Sentinel Python SDK
      run: |
        pip install -e .

    - name: Run tests
      run: |
        pytest

    # Add linter checks
    