name: Pull request to main and closed type and merged

on:
  pull_request:
    types:
    - closed
    branches:
    - main

env:
  PYTHON_VERSION: "3.11"

jobs:

  Release:
    if: 
      github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/')

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Get branch name
      run: |
        echo "${{ toJson(github.event) }}"

    # - uses: actions/checkout@v4
    #   with:
    #     fetch-depth: 0

    # - name: Check if release branch
    #   if: startsWith(env.BRANCH_NAME, 'release/')
    #   run: |
    #     echo "Triggering release workflow for branch: ${{ env.BRANCH_NAME }}"

    # - name: Build project (replace with your build steps)
    #   if: startsWith(env.BRANCH_NAME, 'release/')
    #   run: |
    #     echo "[INFO] Building project"

    # - name: Run tests (replace with your test steps)
    #   if: startsWith(env.BRANCH_NAME, 'release/')
    #   run: |
    #     echo "[INFO] Testing project"

    # - name: Create release (replace with your release script)
    #   if: startsWith(env.BRANCH_NAME, 'release/')
    #   run: |
    #     echo "[INFO] Releasing project"

    # - name: Setup Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: ${{ env.PYTHON_VERSION }}
    #     cache: "pip"

    # - name: Install required packages and tools
    #   run: |
    #     ./scripts/install

    # - name: Bumping versions and tagging
    #   run: |
    #     ./scripts/release

