name: pull-request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-on-pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
