name: release

on:
  push:
   tags:
      - '**'
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade hatch

    - name: Getting Sentinel Python SDK version
      run: |-
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        SDK_VERSION=`hatch version`
        hatch version release
        NEW_SDK_VERSION=`hatch version`
        echo "NEW_SDK_VERSION=$NEW_SDK_VERSION" >> $GITHUB_ENV
        git add src/sentinel/version.py
        git commit -m "Bump version: $SDK_VERSION → $NEW_SDK_VERSION"

    - name: Tagging Sentinel Python SDK and preparing new version
      run: |-
        git tag ${{env.NEW_SDK_VERSION}}
        SDK_VERSION=`hatch version`
        hatch version fix,dev
        NEW_SDK_VERSION=`hatch version`
        git add src/sentinel/version.py
        git commit -m "Bump version: $SDK_VERSION → $NEW_SDK_VERSION"
        git push
        git push --tags
